name: Hello World

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - 'b/**'
  push:
    branches:
      - 'main'
      - 'b/**'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
